#!/bin/bash

planselect(){
prompt="Please select a plan file:"
options=( $(find -maxdepth 1 -type f -name '*.tfplan' -printf '%f\n' | sort -r |xargs -0) )

PS3="$prompt "
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        exit

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        break

    else
        echo "Invalid option. Please select a plan file."
    fi
done    

echo $opt
}

verifydestruction(){
  echo "Are you sure you wish to destroy '$1'?"
  select yn in "Yes" "No"; do
    case $yn in
        Yes ) echo "Proceeding with terraform destroy for '$1'"; break;;
        No ) exit 1;;
    esac
  done
}

sshgenkeypair(){
    echo "Seeing TASKFILEDIR set to '$TASKFILEDIR'"
    echo "Please enter a base filename to use for a newly generated SSH key pair:"
    read basename
    if [ -f "$basename" ]; then
        echo "File '$basename' already exists. Re-run to try another base filename."
        exit 1
    fi
    echo "Please enter a comment for the public key, format like 'username@domain.com' recommended:"
    read keycomment
    ssh-keygen -t ecdsa -b 521 -C "$keycomment" -f "$basename"_ecdsa-sha2-nistp521 -N ''
    echo "Adding JSON compatible version of private key..."
    cat "$basename"_ecdsa-sha2-nistp521 | sed ':a;N;$!ba;s/\n/\\n/g' > "$basename"_ecdsa-sha2-nistp521.forJSON
    echo "SSH key pair generation complete."
}

"$@"